version: "3.7"

services:
  web:
    build: .
    container_name: denorm.njk.localhost
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:plout@db/denorm
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db-orm.njk.localhost
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - POSTGRES_DB=denorm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=plout
      - PGDATA=/var/lib/postgresql/data/denorm
    volumes:
      - /var/lib/postgresql/data/denorm:/var/lib/postgresql/data/denorm
